### ISSUE TITLE
how to mask images automatically

### ISSUE THREAD

**Issue by kw005** [arnaud-ramey/watermark_remover#1]
Is there a way to have a logo/watermark image being automatically detected in the high resolution image and to get the mask image as an result out of it, e.g. logo image + HQ image = mask image => applying "watermark_remover"?

**Comment by arnaud-ramey** [comment]
There is no automatic way to generate the mask to date. 
It might be possible but difficult if the thumbnail is of poor quality (low resolution or JPEG quality factor for instance).
The easiest way is to open the HQ image with an image editor (GIMP or even Microsoft Paint do the job),
and  paint in black on top of the logo. That literally takes under a minute :)
